const ActionTypes = {
	SET_PRODUCTS: 'SET_PRODUCTS',
	SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
	REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCTS',
	LS_PRODUCTS: 'LS_PRODUCTS',
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	LOG_IN: 'LOG_IN',
	LOG_OUT: 'LOG_OUT',
	RESTART_CART: 'RESTART_CART'
};

export default ActionTypes;
